//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProgram
    {
        public int UserProgramID { get; set; }
        public int UserId { get; set; }
        public int ProgramID { get; set; }
    }
}
