//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descriptors_Archive
    {
        public int DescriptorID { get; set; }
        public int CompetencyID { get; set; }
        public string Description { get; set; }
        public short Position { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public Nullable<int> VersionID { get; set; }
    
        public virtual Version Version { get; set; }
        public virtual Competencies_Archive Competencies_Archive { get; set; }
    }
}
