//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningActivities_Archive
    {
        public LearningActivities_Archive()
        {
            this.Competencies_LearningActivities_Archive = new HashSet<Competencies_LearningActivities_Archive>();
        }
    
        public int LearningActivityID { get; set; }
        public int ProgramID { get; set; }
        public string Title { get; set; }
        public string Scenario { get; set; }
        public string TopicsRequired { get; set; }
        public decimal Weeks { get; set; }
        public short Position { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<int> OldLearningActivityID { get; set; }
    
        public virtual Programs_Archive Programs_Archive { get; set; }
        public virtual Version Version { get; set; }
        public virtual ICollection<Competencies_LearningActivities_Archive> Competencies_LearningActivities_Archive { get; set; }
    }
}
