//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace UCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningGoals_Archive
    {
        public LearningGoals_Archive()
        {
            this.Competencies_Archive = new HashSet<Competencies_Archive>();
        }
    
        public int LearningGoalID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public short Position { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public Nullable<int> VersionID { get; set; }
        public int OldLearningGoalID { get; set; }
        public virtual Programs_Archive Programs_Archive { get; set; }
        public virtual Version Version { get; set; }
        public virtual ICollection<Competencies_Archive> Competencies_Archive { get; set; }

        
    }
}
