//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs_Archive
    {
        public Programs_Archive()
        {
            this.LearningActivities_Archive = new HashSet<LearningActivities_Archive>();
            this.ProgramUsers_Archive = new HashSet<ProgramUsers_Archive>();
            this.LearningGoals_Archive = new HashSet<LearningGoals_Archive>();
        }
    
        public int ProgramID { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public Nullable<int> VersionID { get; set; }
    
        public virtual ICollection<LearningActivities_Archive> LearningActivities_Archive { get; set; }
        public virtual ICollection<ProgramUsers_Archive> ProgramUsers_Archive { get; set; }
        public virtual Version Version { get; set; }
        public virtual ICollection<LearningGoals_Archive> LearningGoals_Archive { get; set; }
    }
}
