//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramUsers_Archive
    {
        public int ProgramUserID { get; set; }
        public int UserId { get; set; }
        public int ProgramID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> VersionID { get; set; }
    
        public virtual Programs_Archive Programs_Archive { get; set; }
        public virtual Version Version { get; set; }
    }
}
